### ISSUE TITLE
abstraction for wider use?

### ISSUE THREAD

**Issue by lapetiteclef** [real-logic/artio#137]
This library looks very good. I get the impression artio is abstracted as generic TCP/IP bridge + clustering then a FIX implementation on top?

If so, any chance you could add another service as example for other library use cases? Maybe a clustered "HTTP helloworld GatewayProcess" that is just responding with total number of http get in cluster or similar? 

I can try to implement one I guess . But as Aeron and SBE follower I am more curious about the authors view of such use case and how that should look like. Or if its not recommended at all. 

Reason for asking is that it looks like a overlap with some stuff I use Aeron for, I would love to use this gem instead. Did not find any gitter for this project so I put comment here.

**Comment by mjpt777** [comment]
Artio was not designed as a generic TCP bridge + clustering for Aeron. It was designed to be a reliable clustered FIX gateway that happens to use Aeron. A lot of the concepts in there could be generalised and will be, for example we are producing a generic cluster implementation for Aeron that a future version of Artio could use.

That being said, gateways from messaging to other protocols are often required. We are happy to consider any sponsored development that builds on the Aeron base.

@RichardWarburton was looking into setting up Gitter room for Artio.

**Comment by lapetiteclef** [comment]
ok, think I get it. The application has such likable design that it becomes more interesting than the actual FIX subject. Kind of strange, I never liked any "actor toolkit" (or nio framework). When I finally found one that I liked its not even a toolkit, its an advanced fix handler:) Anyhow, it looks great!

**Comment by RichardWarburton** [comment]
Hi @lapetiteclef,

As Martin says this is really a FIX Engine rather than a TCP Bridge. If you do decide to write your own TCP Bridge then the SenderEndPoint and ReceiverEndPoint classes may offer some inspiration, particularly around reusing Aeron's buffer for sending via TCP that removes a data copy on the critical path.

I'm going to close this issue but feel free to open another one up if you have more specific questions ;)
