### ISSUE TITLE
Add an AsciiSequenceView

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/artio#153]
This should be a view over an underlying buffer that can be used to flyweight a buffer or take a copy of a range. They could be passed in, rather than allocated and returned, and modified to have the appropriate range in the underlying buffer. These could work with SBE to avoid he allocation and do a straight copy in the most efficient way. To be used by the generated codecs instead of storing a char[] and length everywhere.

**Comment by tom-smalls** [comment]
Would it make more sense for the `AsciiSequenceView ` to live in agrona rather than artio? This would allow for better/easier integration with SBE, plus we can think of usages for this outside FIX parsing.

**Comment by tom-smalls** [comment]
We've created a pull request for introducing a AsciiSequenceView. We were wondering if this should be togglable in the generator, where either AsciiSequenceView methods or the array backed string fields are generated.

We haven't added the AsciiSequenceView for encoding. We thought this might be something that is useful for providing a view on buffer backed strings to allow for a more efficient copy, but if we did this we weren't sure of the best approach; holding onto a reference of a AsciiSequenceView until the Fix message is encoded doesn't feel right.

**Comment by RichardWarburton** [comment]
Only thing missing for this issue is the AsciiSequenceView for the Encoder.

**Comment by tom-smalls** [comment]
I just remembered why we didn't implement this for encoders (well, read https://github.com/real-logic/artio/issues/154 again)

``
We haven't added the AsciiSequenceView for encoding. We thought this might be something that is useful for providing a view on buffer backed strings to allow for a more efficient copy, but if we did this we weren't sure of the best approach; holding onto a reference of a AsciiSequenceView until the Fix message is encoded doesn't feel right.
``
Do you have a view regarding implementation?

**Comment by RichardWarburton** [comment]
I'm not sure there's an alternative really other than that approach if we're going to avoid copying. Do you have any ideas or suggestions @mjpt777  ?

**Comment by mjpt777** [comment]
I'm happy for the `AsciiSequenceView` to move to Agrona if that helps.

**Comment by mjpt777** [comment]
I've added an `AsciiSequenceView` to Agrona with this commit. https://github.com/real-logic/agrona/commit/fb24b881f071e4e9a011c1fd2819aa554bc72dad

**Comment by RichardWarburton** [comment]
I'm closing this issue as it's been resolved.
