### ISSUE TITLE
Add the ability for decoders to take a flyweight approach instead of a copying approach

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/artio#154]
Specifically for String based fields. This would be useful for organisations that are just immediately copying from FIX to another internal representation.

**Comment by RichardWarburton** [comment]
Copying the comment from PR discussion to this issue:

We were wondering if this should be togglable in the generator, where either AsciiSequenceView methods or the array backed string fields are generated.

We haven't added the AsciiSequenceView for encoding. We thought this might be something that is useful for providing a view on buffer backed strings to allow for a more efficient copy, but if we did this we weren't sure of the best approach; holding onto a reference of a AsciiSequenceView until the Fix message is encoded doesn't feel right.

**Comment by guoguanglei** [comment]
It is possible to copy lazily?that means invoke getChars in the getter of each field other than when decoding.

**Comment by RichardWarburton** [comment]
That's the idea behind the AsciiSequenceView approach - but it isn't implemented. I don't know if @tom-smalls plans to do so?

Given that the lazy invocation requires a different usage pattern compared to the current approach and the current approach is less error prone I think that we need to have a way of either generating an alternative set of flyweighting codecs if we want to go down this route or a commandline option to the codec generation tool to tell it to generate codecs in this mode. I think the former is probably preferable, even if it will make the codec generation tool a bit slower.

**Comment by tom-smalls** [comment]
I did do an initial implementation of this but came across a few issues around the lazy-ness element of this.

I think we would need to introduce a property of some sort where a user has to opt-in to this due to the dangers around changing an object from being a DTO to a flyweight; there were definitely some issues with resend not working when I did this due to the underlying buffer changing.

**Comment by RichardWarburton** [comment]
I think it might be best to generate two different sets of codecs completely in order to minimise confusion. Does anyone really care about the performance of a resendRequest enough to warrant the complexity of a flyweighting approach? Once you're into resend request territory then your system is already not on a super-latency path.

If you generate two sets of codecs then users can choose to adopt them for latency critical application messages (eg: orders, fills, market data). Artio's internal usage of session codecs can migrate if and when it makes sense.

Would that be ok with you?

**Comment by tom-smalls** [comment]
As in you would have a `QuoteDecoder` and a `QuoteFlyweightDecoder`?

**Comment by RichardWarburton** [comment]
Yes - generating them both. Tbh we could still put them behind optional flags as long as both flags could be turned on at once. Maybe that's the most flexible solution.

**Comment by tom-smalls** [comment]
When I was talking about a property, I was referring to a property that the `CodecGenerationTool` would take rather than something that can be toggled at runtime

**Comment by RichardWarburton** [comment]
Thanks for clarifying - but that was what I assumed you meant. I still think it would be better if we had the option to use both types of simultaneously in a build as it allows Artio users to flip to flyweights without forcing the Session logic to move over to them as well.

**Comment by tom-smalls** [comment]
I just updated the branch and ran all the tests, and everything passed. The branch was 10 months old so guessing changes that have been made in artio have resolved the issues I saw our resend; the FIXME I had added is:

> FIXME: this is going to copy data from ResendRequestDecoder, but the underlying buffer (AsciiBuffer) has been altered due to the test code.
         This occurs (for shouldGapFillAdminMessages) onReplay, where the onTestRequest is processed by the ControlledFragmentAssembler owned by
         the Replayer (captured via ReplayerTest::handler ArgumentCapture), which delegates back to the Replayer instance that then mutates AsciiBuffer
         through Replayer::onFragment

Given this revelation, how would you like to proceed?

**Comment by RichardWarburton** [comment]
Ha - thanks for letting me know.

I guess stepping back I'm interested in the ability to make sure that the different implementations can be tested and that we can either evolve the flyweight approach independently of artio-core or that its acceptance doesn't result in extra work in maintaining artio core from my side. Those are the things that are important from my side.

For example - suppose we integrated the flyweight based codecs and had an either-or approach and in 2 months time we spotted a race condition in artio-core when using flyweight based codecs. I'd either have to fix that or disable the codecs. Keeping them separate reduces the number of configurations that core needs to be tested under and the long term maintenance burden of the project. Does that make sense as a motivation - is there anything I'm missing?

**Comment by tom-smalls** [comment]
Ok, I understand your requirements and the reasoning for using two sets of encoders.

Question: why have artio-core rely on the user to provide all the message codecs it relies on (i.e. session level codecs). Why not just have artio-core be shipped with the codecs it depends on?

**Comment by RichardWarburton** [comment]
Yeah - that's a good question. So I think there's a few different aspects to this:

1. Session codecs vary by FIX version: eg: 4.4 Logon has username and password whilst 4.2 doesn't. So we want to be able to allow users to support different custom FIX configurations. There's various artio-core hooks that interact with the FIX messages themselves - eg: the ValidationStrategy, AuthenticationStrategy.and PersistenceStrategy - and I think it would be an inconsistent and awkward experience for users to have to deal with a different set of non-customisable session codecs for those strategies when they're generating the correct codecs.
1. Dogfood our generated codecs.
1. Avoid hand-writing codecs that we're generating anyway.

Even if we split out artio-core's codecs there's still a different programming model here between flyweighting and copying, so it's still something that needs a bit of highlighting / flagging.

Getting back to this particular issue - if you want to PR your existing changes (or even just point me at the branch) then I'm happy to do the work to split things out so you're not on the hook to do the legwork to meet my requirements.

**Comment by tom-smalls** [comment]
So I can't answer for the various strategies you are referring but we have had to solve similar problems around supporting different versions of FIX.

How we currently deal with this for encoding / sending messages is for our FixEngine to take an `Encoder` and then perform the following on it:

```
final SessionHeaderEncoder headerEncoder = encoder.header();
            headerEncoder
                    .beginString(beginString)
                    .targetCompID(targetCompId)
                    .senderCompID(senderCompId)
                    .msgSeqNum(msgSeqNum)
                    .sendingTime(timestampEncoding, 0, timestampLength);

            final long offsetAndLength = encoder.encode(fixSendBuffer, 0);
            final int offset = Encoder.offset(offsetAndLength);
            final int length = Encoder.length(offsetAndLength);

            final int prepare = publisher.prepare();
            final MutableDirectBuffer buffer = publisher.buffer();
            buffer.putBytes(prepare, fixSendBuffer, offset, length);
            sendFixMessage(length, prepare, buffer);
```

Where beginString, targetCompId, and senderCompId are provided via some configuration. This is part of a send method that is used for both sending session and application level FIX messages. For session level FIX messages we use our own generated codecs that live as part of our FixEngine (nothing hand-written!).

Agreed this is a diversion from this issue but wanted to highlight what we are doing in case it's something that is useful for artio-core!

I can raise a PR; do you want it so flyweight is protected by a run-time or generation-time flag?

**Comment by RichardWarburton** [comment]
Thanks for the observation - definitely something we could think about. We'll need to figure out a better method if / when someone really wants multiple session codecs in the same process.

Generation-time flag please.

**Comment by tom-smalls** [comment]
It just gives us the flexibility to be FIX version agnostic and has the advantage of not having depending on codecs provided by a third party!

I'll should be able to get the PR done over the weekend

**Comment by tom-smalls** [comment]
I've raised the PR for this.

It was a lot more difficult than I expected because of the number of places where we assign and read from the string fields. There is definitely room for refactoring on this but wanted to just get something into unblock the work you want to do.

I also wasn't sure the best way to test this. We can't re-use / use the `DecoderGeneratorTest` due to the static compilation of the decoders under test.

**Comment by RichardWarburton** [comment]
Merged.
