### ISSUE TITLE
artio-core: Compilation error: Missing: uk.co.real_logic.artio.messages

### ISSUE THREAD

**Issue by babhijit** [real-logic/artio#179]
OS: Windows 10 Pro
IDE: IntelliJ CE

For some reason the package "uk.co.real_logic.artio.messages" is not present.

**Comment by mjpt777** [comment]
Try building on the command line with `gradlew` first in the project directory.

```sh
    ./gradlew
```

**Comment by babhijit** [comment]
That helped! Thanks!
