### ISSUE TITLE
How about add a new parameter "offset"(default is 0)? so that we can pass an segment of an byte buffer.

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#187]
https://github.com/real-logic/artio/blob/37bbe9c4fc5553a645f5dbcc81c6fb9f64e14508/artio-codecs/src/main/java/uk/co/real_logic/artio/dictionary/generation/EncoderGenerator.java#L379

**Comment by RichardWarburton** [comment]
Hi Gary,

Yes - this makes sense to me as an improvement. Will implement tomorrow.

**Comment by guoguanglei** [comment]
Hi, Richard

Actually we am expecting add a offset field to the encoder POJO to avoid the copy(see example below).
Same logic to the AsciiSequenceView in the decoder POJO, we are expecting only copy when necessary in our callback.
So it make sense to us to provide an option to choose between AsciiSequenceView and char copying versions at the codec generation time. #188 

Take "symbol" field in NewOrderSingleEncoder as an example:
```Java
    private byte[] symbol = new byte[1];

    private int symbolOffset = 0;

    private int symbolLength = 0;

    public NewOrderSingleEncoder symbol(final byte[] value, final int offset, final int length)
    {
        symbol = value;
        symbolOffset = offset;
        symbolLength = length;
        return this;
    }
```

**Comment by RichardWarburton** [comment]
Oh I see. Yes, that's a better approach and more consistent with the other byte[] version. Will change it over now. Thanks for your feedback.

**Comment by RichardWarburton** [comment]
@guoguanglei - right I've pushed a fix for that, thanks.
