### ISSUE TITLE
Can "getChars" generation removed?We can use AsciiSequenceView to copy when necessary.

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#188]
https://github.com/real-logic/artio/blob/37bbe9c4fc5553a645f5dbcc81c6fb9f64e14508/artio-codecs/src/main/java/uk/co/real_logic/artio/dictionary/generation/DecoderGenerator.java#L1165

**Comment by RichardWarburton** [comment]
I think having thought about this issue it's best to keep the getChars() version for now.

NB: after the latest Aeron release we've deprecated our own AsciiSequenceView and started using the one from Aeron.
