### ISSUE TITLE
The newly introduced AeronArchive support creates garbage in 0.16

### ISSUE THREAD

**Issue by mprusakov-rbc** [real-logic/artio#209]
https://github.com/real-logic/artio/blob/022ef71262593db5a328be173fd3d5c2750deb9d/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/Replayer.java#L194 creates a lambda in a loop and creates a lot of garbage. To reproduce modify https://github.com/real-logic/artio/blob/master/artio-samples/src/main/java/uk/co/real_logic/artio/client/SampleClient.java to send test messages in a loop and measure garbage

**Comment by RichardWarburton** [comment]
Thanks @mprusakov-rbc - pushed a fix to this issue.
