### ISSUE TITLE
IndexOutOfBoundsException in Indexer

### ISSUE THREAD

**Issue by ashananin** [real-logic/artio#212]
Master as of 17-Dec-2018:

Dec 18 10:19:10 prod java[16837]: java.lang.IndexOutOfBoundsException: index=2097176 length=4 capacity=2097176
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1374)
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.UnsafeBuffer.putInt(UnsafeBuffer.java:521)
Dec 18 10:19:10 prod java[16837]: at uk.co.real_logic.artio.storage.messages.ReplayIndexRecordEncoder.sequenceIndex(ReplayIndexRecordEncoder.java:314)
Dec 18 10:19:10 prod java[16837]: at uk.co.real_logic.artio.engine.logger.ReplayIndex$SessionIndex.onRecord(ReplayIndex.java:240)
Dec 18 10:19:10 prod java[16837]: at uk.co.real_logic.artio.engine.logger.ReplayIndex.onFragment(ReplayIndex.java:160)
Dec 18 10:19:10 prod java[16837]: at uk.co.real_logic.artio.engine.logger.Indexer.onFragment(Indexer.java:150)
Dec 18 10:19:10 prod java[16837]: at io.aeron.Image.controlledPoll(Image.java:349)
Dec 18 10:19:10 prod java[16837]: at io.aeron.Subscription.controlledPoll(Subscription.java:244)
Dec 18 10:19:10 prod java[16837]: at uk.co.real_logic.artio.engine.logger.Indexer.doWork(Indexer.java:71)
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
Dec 18 10:19:10 prod java[16837]: at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
Dec 18 10:19:10 prod java[16837]: at java.lang.Thread.run(Thread.java:748)

The exception is persistent -- once printed, keeps on printing same message "index=2097176 length=4 capacity=2097176" until shutdown.

**Comment by ashananin** [comment]
seems like there is bug in ReplayIndex.SessionIndex.onRecord:
```
final long beginChangePosition = beginChange(buffer);
final long changePosition = beginChangePosition + RECORD_LENGTH; // <- changePosition is out of bounds
...
final int offset = offset(beginChangePosition, capacity); // <- here we rollover if begin is out of bounds, but not END

```

**Comment by RichardWarburton** [comment]
Thanks for investigating. Looks like this bug was introduced when I improved the replayer performance the other week. Can I confirm that you aren't setting a custom `EngineConfiguration.replayIndexFileSize()` ?

**Comment by RichardWarburton** [comment]
So I've pushed what I think is a fix for this issue. I don't think the issue that you're raising should happen because the recordCapacity of the replay index file should be a multiple of the RECORD_LENGTH. But I did notice when I investigated that we incorrectly initialise the beginChangePosition at the start to not be a multiple of RECORD_LENGTH, so I've fixed that and added more validation.

If you see this issue crop up again please re-open.

**Comment by ashananin** [comment]
yeah, fix looks good, thanks!
