### ISSUE TITLE
Enhancement of class MutableAsciiBuffer method putAsciiFloat

### ISSUE THREAD

**Issue by ariksher-nex** [real-logic/artio#227]
it seems that if decimalFloat represents value between 0 (exclusive) and 1 (exclusive)
the method putAsciiFloat will output the value **without** leading zero.
can be seen in test class **DecimalFloatEncodingTest** relevant entries : 
            {".995", 995L, 3}
            {"-.995", -995L, 3},
            {".6", 6L, 1},
            {".06", 6L, 2},
            {"-.6", -6L, 1},
            {"-.06", -6L, 2},
            {".92117125", 92117125L, 8},
            {"-.92117125", -92117125L, 8},
            {".92125", 92125L, 5},
            {"-.92125", -92125L, 5},
            {".00007875", 7875, 8},
            {"-.00007875", -7875, 8},

i think that need had behavior flag for the MutableAsciiBuffer to control whether to add this leading zero or not, the default would be without, just to preserve the existing behavior.
proposed flag name : **outputLeadingZeroForDecimalFloat**  (default value is false)

**Comment by RichardWarburton** [comment]
Can you explain what the need is providing the leading zeros? As far as I know the FIX spec is fine with you omitting the leading zeros. I've not so far encountered any systems that don't accept this, however, if you have then I'd be interested to know of it.

I don't like the proposed solution to add another configuration option to control this behavior. If leading zeros is needed then it's probably simpler to just produce leading zeros everywhere, you're definitely against the FIX specification if you don't parse "0.1". I've been considering going down this route myself btw just to remove the risk of hitting a system that didn't support leading zeros.

**Comment by ariksher-nex** [comment]
we're rewriting our system, and the old system does send leading zero, for example: "0.1"
so our customers expect it, currently not sure if they handle values without leading zeros (in this example ".1").

I suggested the solution of flag just to preserve your existing behavior,
if you don't like it, i'm with you, lets make it consistent and always have leading zero.

**Comment by ariksher-nex** [comment]
yep, I will do so.

**Comment by ariksher-nex** [comment]
BTW I encountered some issue, can you please take a look at issue #228
