### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by mprusakov-rbc** [real-logic/artio#238]
Are there any plans to support SSL? Thanks.

**Comment by RichardWarburton** [comment]
There are no current plans to support SSL/TLS. If you want TLS support directly in Artio itself and are willing to sponsor its development then I would be happy to discuss the options given a tradeoff between cost and performance.

There are available TLS terminators that present as a TCP socket on one side and a TLS socket on the other, for example stunnel and haproxy, these can be used with Artio.
