### ISSUE TITLE
Missing messages on Maker start

### ISSUE THREAD

**Issue by stepan2271** [real-logic/artio#242]
In the following scenario:
1. maker FixEngine starts;
2. connection from remote established;
3. FixLibrary is created and connecting to engine;
4. FixLibrary requests session from engine;
In some circumstances, when 2) happens on one thread and 3)-4) happens on another one at approximately the same time, even when library requests session with full replay parameters:
```
library.requestSession(surrogateSessionId, 0, 0, CommonConfiguration.DEFAULT_REPLY_TIMEOUT_IN_MS)
```
**there may be no replay at all**, however we can see FIX messages that reach FixEngine in detailed log (running with flag ``-Dfix.core.debug=true``).
I did not manage to reproduce the problem when steps 3) and 4) were artificially delayed. So, it seems that the issue is indeed associated with some concurrent processing of events 2), 3) and 4).
We work on creating a standalone test to reproduce it.

**Comment by RichardWarburton** [comment]
This sounds like a bug, looking forward to seeing the reproduction. Are you using the latest version of Artio? Can I also confirm that the reply object for `requestSession` completes correctly and doesn't have an error in it? Can you also confirm that there isn't a "Missing Messages for <sessionId>" message in the debug log?

Just a few notes: when you replay those messages they will be replayed from the message archive, but -Dfix.core.debug=true will print them out once they hit the Framer. This still sounds like a bug though, possibly indicates that if the archiver is behind the Framer then there may be a catchup replay gap. I've just looked at the code though and we do check for that case.

**Comment by stepan2271** [comment]
1. We rebuilt artio jar from master (``commit fd9e3b4463aecf92d9d0b688333c31b68cde2f5f``) and got the same problem.
2. There are no messages "Missing Messages for "
3. **Indeed, I realized that  we got an error** ``uk.co.real_logic.artio.FixGatewayException: Not connected to the Gateway`` **in Reply**. However it doesn`t take place when some disconnects may happen, it happens on start. So library was just created with connect method. I guess that there are no guarantees that SessionExistsHandler will be triggered after the library will be connected in this case. Is it true? How to handle this situation? Can I just requestSession later with the same replay strategy?

**Comment by RichardWarburton** [comment]
So I think the situation that you've run into is that the library itself has disconnected from the Engine. In order to keep yourself connected you need to ensure that the `FixLibrary.poll()` method is called regularly in order to make sure that the library and engine don't time each other out.

I don't think there's a good way to handle the missing SessionExistsHandler call with the current Artio API. You're right that's an oversight and I'll file an issue on it.

You can definitely call requestSession later on and get the messages replayed.
