### ISSUE TITLE
Make encoder/decoder parent package configurable

### ISSUE THREAD

**Issue by ashananin** [real-logic/artio#245]
1) uk.co.real_logic.artio.dictionary.CodecGenerationTool has PARENT_PACKAGE property to **set parent package** for all generated encoder/decoder classes. 
2) uk.co.real_logic.artio.engine.EngineConfiguration **hardcodes** package for decoders: 

`import uk.co.real_logic.artio.decoder.*;`

Above limits user to just one version of session dictionary per classloader

**Comment by RichardWarburton** [comment]
We haven't decided how we want to support multiple session dictionaries per class loader yet. When the right direction for that feature is decided upon we'll move forward with it.

An alternative might to get all the Session codecs to have common interfaces or abstract classes for example and to continue to generate them into a common folder but have different folders for implementations.
