### ISSUE TITLE
Add on build instructions

### ISSUE THREAD

**Issue by sh-abhi** [real-logic/artio#261]
Trying to play around with the project locally; but having some issues when trying to build it and run the tests.

Do we have any particular set of instructions? I'm happy to volunteer and try to piece them together if it's outstanding.

If it helps, I'm currently unable to build the project on my local machine since the`uk.co.real_logic.artio.decoder` doesn't appear to exist within the project.

Any suggestions are welcome.

**Comment by juddgaddie** [comment]
What OS are you on?

Have you tried ./gradlew

**Comment by RichardWarburton** [comment]
If you just want to compile Artio then the README points you should use ./gradlew. If you want to set the codec generation as part of the build process of an external project then take a look at https://github.com/real-logic/artio/wiki/Codecs. If you just want to use Artio then it's in maven central - https://search.maven.org/search?q=artio.

**Comment by sh-abhi** [comment]
Apologies @juddgaddie, @RichardWarburton, some local issues when running `./gradlew` yesterday; I resolved them and it works smoothly.
