### ISSUE TITLE
Why call indexedUpTo in below location?

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#269]
https://github.com/real-logic/artio/blob/d7810c7c42b5559a20d5cecfbb3c54752bcab6fc/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/ReplayIndex.java#L236

Call indexedUpTo in above location will always cause an replay when restart(the position already advanced with some non fix messages)

Can we move this to onFragment method like what SequenceNumberIndexWriter did?

**Comment by RichardWarburton** [comment]
Makes sense as an improvement. I think it can be moved.
