### ISSUE TITLE
Supporting in Multiple FIX Version in Single Exchange

### ISSUE THREAD

**Issue by willyhalim** [real-logic/artio#272]
Hi,

Is is possible to support multiple fix version multi session in One Single Exchange ?

My Scenario is need to host one exchange that can accept multi session different fix version.

I tried with below but i got the hearbeat back in FIX4.4
1. Start the Exchange Server ( using the SampleServer.java provided )
2. have my FIX4.2XML converted to Artio Codec and send TestRequest. 
    The test request was sent properly but i got the heartbeat back in FIX4.4 version

8=FIX.4.29=2535=1112=Hello World234510=144
8=FIX.4.49=7735=049=BAMLFR856=BAMLFR834=252=20190522-03:28:21.563112=Hello World234510=114

**Comment by RichardWarburton** [comment]
We currently don't support this feature. Would you be interested in sponsoring its development?

**Comment by RichardWarburton** [comment]
Closing this issue due to lack of response.
