### ISSUE TITLE
Increase the frequency of persisting sequence number

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#274]
https://github.com/real-logic/artio/blob/97c8e45b82aac191158bb1aa9279bd5b12e0708d/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/SequenceNumberIndexWriter.java#L185

When use Aeron IPC, the default term buffer length is 64M, this may cause a big sequence number gap between the memory and the persistent file if Artio did not stop gracefully.

**Comment by RichardWarburton** [comment]
Thanks for the report Gary, will look into it.

**Comment by RichardWarburton** [comment]
This index file now flushes on a configurable timeout, with the default set to 10 seconds. Does that sound right?

**Comment by guoguanglei** [comment]
Thank you Richard, make sense to me.
