### ISSUE TITLE
MessageDecoder interface to represent the message decoders

### ISSUE THREAD

**Issue by lucianoviana** [real-logic/artio#275]
Currently, all message decoders implement the `Decoder` interface and there's no way to access data common to all messages like the header without having to cast to a specific message decoder class. By adding a `MessageDecoder` interface extending the `Decoder`, we could access these common data in an abstract level once all the messages decoders would implement this new interface.

As an example, we would have:

- `Quote implements MessageDecoder` 
- `MessageDecoder extends Decoder`

**Comment by tom-smalls** [comment]
For the `Encoder`, there is already a `header` method that returns `SessionHeaderEncoder`. Is this the sort of thing you are after?

Not sure a `MessageDecoder` is needed.

**Comment by RichardWarburton** [comment]
The desire is to be able to get the HeaderDecoder out of any message type.

**Comment by lucianoviana** [comment]
cool, thx
