### ISSUE TITLE
UtcTimestampEncoder#encode parameter assumes alignment with EpochFractionFormat

### ISSUE THREAD

**Issue by clifford** [real-logic/artio#276]
The encode method on UtcTimestampEncoder according to the javadoc can accept either milliseconds or microseconds. However, within encodeFraction the calc for localSecond assumes the parameter is in alignment with the constructor parameter EpochFractionFormat. 

As an example, if I initialise UtcTimestampEncoder with MICROSECONDS and then later call encode with milliseconds, then the date will be miscalculated.

```
      final UtcTimestampEncoder encoder = new UtcTimestampEncoder(MICROSECONDS);
        String expected = "20190603-17:00:00.123";
        long myEpochMillis = toEpochMillis(expected);

        final int length = encoder.encode(myEpochMillis);
        assertEquals(expected, new String(encoder.buffer(), 0, length, US_ASCII));
```
Result will be:

Expected :20190603-17:00:00.123
Actual   :**19700119**-01:13:01.200123

I would be happy to submit a patch, if you'd like me to do so?

Thanks
Cliff

**Comment by RichardWarburton** [comment]
Would the patch be a javadoc clarification? If so yes, totally happy. If not please clarify what you had in mind.

**Comment by clifford** [comment]
Was thinking there are several options:

That encode method should possibly take 2 parameters.
First is epochFraction and the second being a TimeUnit (millis,micros,nanos), if the unit differes from the constructor parameter EpochFractionFormat then:

**Option 1**
Raise a  warning that time usint differs 

**Option 2** 
scale the parameter to suit constructor parameter EpochFractionFormat

**Option 3** 
Make the javadoc for encode more explicit that the parameter passed in should match EpochFractionFormat

I'm sure you have some more elegant solutions.

**Comment by RichardWarburton** [comment]
To be honest I'd rather the Javadoc just clarified that the format must be the same. The thing is that this is a format for a timestamp in a protocol - so the counter parties would have to agree and document what the format for the timestamp is ahead of time anyway. Putting the wrong precision of timestamp in is the kind of bug that should be caught quite early with testing, so I don't think it warrants a runtime check for every encode.

**Comment by RichardWarburton** [comment]
There's also the update method as well, which will have the same situation.

**Comment by clifford** [comment]
makes perfect sense Richard
