### ISSUE TITLE
DecimalFloat reset to NAN

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#279]
https://github.com/real-logic/artio/blob/c72b15df71430b241681d9d1ffc337d017695259/artio-codecs/src/main/java/uk/co/real_logic/artio/fields/DecimalFloat.java#L100

I think it make more sense to reset to a NAN?

**Comment by RichardWarburton** [comment]
Thanks for the suggestion Gary. It sounds like a good idea and I've pushed a commit for this change. It is a breaking change though. I've also updated the MISSING_VALUE field to be a NaN as well as that is what you're expected to compare the reset value with.
