### ISSUE TITLE
Tag 369 not populated when rejecting login

### ISSUE THREAD

**Issue by lucianoviana** [real-logic/artio#296]
Artio is not populating tag 369 (LastMsgSeqNumProcessed) when rejecting a login due to msgSeqNum lower than expected.

Example:

`8=FIX.4.4|9=140|35=A|34=2|49=party1|52=20190827-09:51:42.077|56=BTQFIX|98=0|108=60|553=party1|554=abc|10=239|`

`8=FIX.4.4|9=135|35=5|49=BTQFIX|56=party1|34=10|52=20190827-09:51:42.383|369=0|58=MsgSeqNum too low, expecting 6 but received 2|10=039|`

**Comment by RichardWarburton** [comment]
Fixed.
