### ISSUE TITLE
UtcTimestampEncoder adds spaces for zero-millis timestamps

### ISSUE THREAD

**Issue by mostr** [real-logic/artio#298]
`UtcTimestampEncoder` doesn't format zero-millis timestamp properly. 

We're using it the following way (Scala):
```
      val utcEnc = new UtcTimestampEncoder
      utcEnc.encode(t.millis)
      utcEnc.buffer
```

and it looks like for timestamps that have zero millis, buffer doesn't get trimmed down (or filled with zeros), instead it gets 4 spaces (dot + 3 chars for millis) which results with requests being rejected with `Error code UnparsableValue occurred while parsing a FIX message.  Tag ID is 60. `

Following is the message that gets sent with incorrect date format:
```
{
  "MessageName": "TradeCaptureReportRequest",
  "header": {
    "MessageName": "Header",
    "BeginString": "FIX.4.4",
    "MsgType": "AD",
    "SenderCompID": "xxx",
    "TargetCompID": "LMXBL",
    "SendingTime": "20190830-09:14:00.465",
  }
  "TradeRequestID": "xxx",
  "TradeRequestType": "1",
  "TrdCapDtGrp":  {
    "MessageName": "TrdCapDtGrp",
    "DatesGroup": [
      {
        "MessageName": "DatesGroup",
        "TransactTime": "20190830-09:13:50    ",  // <----------- see here
      },
      {
        "MessageName": "DatesGroup",
        "TransactTime": "20190830-09:14:00.465",
      }
    ]
  }
}
```

**Comment by RichardWarburton** [comment]
The return value of the `encode` method is the length of the number of bytes in the buffer to use. That should be passed into the appropriate field as a length value. For example:

```
final int transactTimeLength = transactTime.encode(System.currentTimeMillis());
newOrderSingle.transactTime(transactTime.buffer(), transactTimeLength)
```
