### ISSUE TITLE
 tag information is not returned in exception caused during parsing the FIX message

### ISSUE THREAD

**Issue by AmitA396** [real-logic/artio#301]
The tag that caused the exception in parsing of FIX message should be returned in the exception so that it can be used to generate SessionReject message back to sender.

**Comment by RichardWarburton** [comment]
@AmitA396 do you have any example FIX messages here that generate bad error messages?

**Comment by RichardWarburton** [comment]
So I think this is fixed to be honest but I'm going to leave this issue open for a bit until there's confirmation that there isn't another case within FIX messages that needs working on.

**Comment by AmitA396** [comment]
@RichardWarburton - it was happening when a customer sends a character on a tag which accepts only integer value.

**Comment by RichardWarburton** [comment]
Great - thanks for clarifying the work I've done on this today covers that case.
