### ISSUE TITLE
New connections not accepted by the fix server due to failure in index writing

### ISSUE THREAD

**Issue by dilanperera87** [real-logic/artio#371]
We've developed a fix trading gateway using artio fix engine 0.53. There is a health checker running in our production environment and service availability is checked by making a TCP connection to fix gateway service port in configured time interval.
Gateway was restarted few times for new deployments and after few weeks, the fix gateway stopped accepting new connections from clients. After our investigations, we've found that the socket limit was exceeded in the machine and there are lots of TCP sockets are in **CLOSE_WAIT** state and all of them server side sockets of the fix gateway instance. A TCP socket will be at **CLOSE_WAIT** state if the socket is not closed by the server side correctly.
After restarting the fix gateway all TCP sockets in **CLOSE_WAIT** state were released. But same happened again after running fix gateway for few days.
Same behavior was observed in another development environment and we were able to enable debug logs in fix library level and we have following findings. In this environment we've upgraded the artio version to 0.63.

**_Note:_** Aeron archive context threading mode is set to **ArchiveThreadingMode.SHARED**.

1. The Indexer is stuck at below callstack
`"[Indexer,Indexer,Replayer]" #47 prio=5 os_prio=0 tid=0x00007f69b0d5f800 nid=0x2276 runnable [0x00007f4f301f9000]
   java.lang.Thread.State: RUNNABLE
	at uk.co.real_logic.artio.engine.logger.IndexedPositionWriter.indexedUpTo(IndexedPositionWriter.java:148)
	at uk.co.real_logic.artio.engine.logger.IndexedPositionWriter.checkPosition(IndexedPositionWriter.java:191)
	at uk.co.real_logic.artio.engine.logger.IndexedPositionWriter.trackPosition(IndexedPositionWriter.java:180)
	at uk.co.real_logic.artio.engine.logger.IndexedPositionWriter.update(IndexedPositionWriter.java:226)
	at uk.co.real_logic.artio.engine.logger.ReplayIndex.onFragment(ReplayIndex.java:224)
	at uk.co.real_logic.artio.engine.logger.ReplayIndex.onFragment(ReplayIndex.java:137)
	at uk.co.real_logic.artio.engine.logger.Indexer.onFragment(Indexer.java:171)
	at io.aeron.Image.controlledPoll(Image.java:368)
	at io.aeron.Subscription.controlledPoll(Subscription.java:238)
	at uk.co.real_logic.artio.engine.logger.Indexer.doWork(Indexer.java:84)
	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.lang.Thread.run(Thread.java:748)`

1. Since the Replayer also runs in the same thread, it was unable to process the ReplayerCommandQueue. This was identified by adding some log entries in ReplayerCommandQueue class and observed that poll method is not getting called.

1.  After receiving **64** client connections, the ReplayerCommandQueue becomes full and not able to add new commands to the queue.

1. Then Framer is waiting indefinitely at ReplayerCommandQueue.offer() since the queue is full.

1. There were three fix library instances configured in our development environment and all 3 library instances detected application heartbeat failures and then disconnected with engine.
`1591982896949:orderEntryThread[LIBRARY_CONNECT]1973102458: Disconnected from [aeron:ipc]
1591982896949:orderEntryThread[LIBRARY_CONNECT]1973102458: Attempting to connect to aeron:ipc
1591982896949:orderEntryThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=1973102458|correlationId=740863822898160617|libraryName=''
1591982897044:dropCopyThread[LIBRARY_CONNECT]-2079952683: Disconnected from [aeron:ipc]
1591982897044:dropCopyThread[LIBRARY_CONNECT]-2079952683: Attempting to connect to aeron:ipc
1591982897044:dropCopyThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=-2079952683|correlationId=2197614993988081857|libraryName=''
1591982897228:marketDataThread[LIBRARY_CONNECT]108548258: Disconnected from [aeron:ipc]
1591982897228:marketDataThread[LIBRARY_CONNECT]108548258: Attempting to connect to aeron:ipc`

1. Libraries are trying to connect to the engine continuously and below log entry is printed. 
`1591982897228:marketDataThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=108548258|correlationId=4207855653798623425|libraryName=''
1591982899450:orderEntryThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=1973102458|correlationId=740863822898160618|libraryName=''
1591982899545:dropCopyThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=-2079952683|correlationId=2197614993988081858|libraryName=''
1591982899729:marketDataThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=108548258|correlationId=4207855653798623426|libraryName=''
1591982901951:orderEntryThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=1973102458|correlationId=740863822898160619|libraryName=''
1591982902047:dropCopyThread[GATEWAY_MESSAGE][LibraryConnect](sbeTemplateId=17|sbeSchemaId=666|sbeSchemaVersion=10|sbeBlockLength=12):libraryId=-2079952683|correlationId=2197614993988081859|libraryName=''`

Since it was like an issue with writing index files, we've cleaned all archive files and restarted the gateway and then gateway was able to accept new connections continuously. 

Is there any known issues like this? 
What could be the reason for IndexedPositionWriter getting stuck at indexedUpTo method?
Since cleaning the archive files is not possible in a production environment, what is the recommended way of restarting a gateway instance without affecting the state of the gateway.

**Comment by RichardWarburton** [comment]
Your stacktrace doesn't appear to be possible in version 0.53 as it contains line numbers that don't exist in that version of IndexedPositionWriter:

https://github.com/real-logic/artio/blob/0.53/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/IndexedPositionWriter.java

**Comment by dilanperera87** [comment]
Sorry I forgot to mention that in development environment we linked it to 0.63.

**Comment by RichardWarburton** [comment]
I don't think I've seen a bug like this fixed since 0.63 but I would see if it is replicated in the latest release anyway as some changes have been made to the indexer since then.

Does your error handler tell you anything? The only way I can think of that your indexer sits there is perhaps if the indexed position buffer is full?

**Comment by dilanperera87** [comment]
We haven't set custom error handler in it. 
What is the maximum size of indexed position buffer? 
In our development environment this happened within 2-3 minutes after starting the gateway with existing message archive. Is it possible to indexed buffer gets filled so fast?

**Comment by dilanperera87** [comment]
@RichardWarburton Is there any update on above queries?

**Comment by RichardWarburton** [comment]
The replay position buffer size is 4K. I would say that it's unlikely that it gets filled up very fast unless you have a FixLibrary connecting and disconnecting a lot - because it's keyed on the aeron sessionId.

Have you investigated whether this happens in the latest release?

**Comment by dilanperera87** [comment]
In our scenario there are lots of connect and disconnect events because our health checker connects to fix service port configured interval ( every 30 seconds).

**Comment by dilanperera87** [comment]
> Have you investigated whether this happens in the latest release?

We haven't linked to the latest version yet. Currently we are in 0.63.

**Comment by RichardWarburton** [comment]
Closing, probably fixed in PR #372
