### ISSUE TITLE
library busy-loops while polling on disconnected sessions if engine configured in single-library mode

### ISSUE THREAD

**Issue by kwbc** [real-logic/artio#392]
It seems disconnected sessions aren't removed LibraryPoller.sessions when the engine is configured in single-library mode.  And due to a quirk in Session.poll, poll can always returns a non-zero value if disconnected.  I'm guessing because nextRequiredInboundMessageTimeInMs is never changing.  
```java
if (time >= nextRequiredInboundMessageTimeInMs)
{
    if (awaitingHeartbeat)
    {
        // Drop when back pressured: retried on duty cycle
        requestDisconnect();
    }
    else if (isActive)
    {
        final int sentSeqNum = newSentSeqNum();
        if (proxy.sendTestRequest(
            sentSeqNum, TEST_REQ_ID, sequenceIndex(), lastMsgSeqNumProcessed) >= 0)
        {
            lastSentMsgSeqNum(sentSeqNum);
            awaitingHeartbeat = true;
            incNextReceivedInboundMessageTime(time);
        }
    }
    actions++;
}
```

Should disconnected sessions be removed from LibraryPoller.sessions?

**Comment by RichardWarburton** [comment]
I don't think so. The lifecycle of sessions within sole library mode is different. Sessions stick to the sole library rather than being released and re-acquired. It's a simpler mode in terms of the usage patterns in general.

**Comment by kwbc** [comment]
Ok, but it still shouldn't spin on disconnected sessions though.  The problem is that actions is always incremented if time >= nextRequiedInboundMessageTimeInMs, but nextRequiedInboundMessageTimeInMs is only updated if the session is active.

**Comment by RichardWarburton** [comment]
You're right - thanks, will push a fix.

**Comment by kwbc** [comment]
Looks good.  Thanks for the quick fix.
