### ISSUE TITLE
Conflicting archive directories in example

### ISSUE THREAD

**Issue by irisliu88** [real-logic/artio#398]
When using the examples `ExchangeApplication` and `BuyerApplication` with their respective media drivers, we are not able to replay archived messages properly since they use the same `archiveDirectoryName`. I propose we update the example to use different `archiveDirectoryName` fields. Also any identification of conflicting archive directories being used would also be helpful.

**Comment by RichardWarburton** [comment]
Thanks for the spot. I've updated the example accordingly. Conflicting archive detection is probably best dealt with at the responsibility of the Aeron Archiver.
