### ISSUE TITLE
FIXP + SOFH + SBE API support

### ISSUE THREAD

**Issue by cmunger** [real-logic/artio#400]
Hello,

Unless I misunderstood the codebase, I see that the CME Ilink is implementing under the hood a good part these technologies (FIXP and SOFH), which are unfortunately only usable if you use CME Ilink and as a client. Would be great if artio could provide a stable API to build client or servers using this technology stack, independent of the CME messages format, and reuse this API for your ILink impl. This would allow artio API users to build to notch low latency FIXP applications.

**Comment by RichardWarburton** [comment]
Yeah - it's an idea I've given thought to. Any large-scale Artio development - like iLink3 support - has commercial backing. A sponsor who is willing to fund development. The sponsor for iLink3 only requested iLink3 support - not a generic FIXP implementation. Are you interested in sponsoring work in this area?

**Comment by cmunger** [comment]
Yes i understand it's quite a big job without funding. We will soon start to adopt artio in my company with regular fix, we'll see if we plan to provide to our customers FIXP, I'll be happy to help in such case, I guess we can close the issue.
