### ISSUE TITLE
Can we use OffsetEpochNanoClock to get the nano time instead of Clock.systemNanoTime()?

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#406]
@RichardWarburton , Can we use OffsetEpochNanoClock to get the nano time instead of Clock.systemNanoTime() which will be consistent with iLINK3?

https://github.com/real-logic/artio/blob/6bff3e6c2575b67ee4e7968151814af35e1876df/artio-core/src/main/java/uk/co/real_logic/artio/CommonConfiguration.java#L223

**Comment by RichardWarburton** [comment]
Yes - makes total sense.
