### ISSUE TITLE
Missing unsigned shift in the Encoder?

### ISSUE THREAD

**Issue by tomb85** [real-logic/artio#426]
Hi, was it intentional to use signed right shift when extracting `offset` from the `result` in the `Encoder`? It seems it will cause an issue if the offset is very large. 

```java
public interface Encoder extends CharAppender
{
    int BITS_IN_INT = 32;

    static int offset(final long result)
    {
        return (int)(result >> BITS_IN_INT);
    }

   ...
}
```

**Comment by RichardWarburton** [comment]
Hi Tom,

Maybe I'm being dumb - but I'm not sure what the problematic case is here. One thing I will note is that the usage of the Encoder.result() always assumes that length and offset are positive - which they should be within Artio. In this context I don't think there's any difference between signed and unsigned right shift. I can't reproduce an issue with Integer.MAX_VALUE as the input offset.

**Comment by tomb85** [comment]
hi @RichardWarburton - sorry it was me being dumb trying to overthink it. I assumed you are treating the `result` and `offset` as unsigned `int` when packing them into `long` , in that case the max value for either `offset` or `result` would be 2^32 -1 rather than `Integer.MAX_VALUE`. Since the max offset and result will always have the sign bit set to 0 then, as you pointed out, there is no difference whether you use signed or unsigned shit.
