### ISSUE TITLE
It is possible to redefine numeric constants such as DecimalFloat.ZERO

### ISSUE THREAD

**Issue by michaelszymczak** [real-logic/artio#452]
I have noticed that some known predefined DecimalFloat values are prone to be corrupted if assigned directly.

![image](https://user-images.githubusercontent.com/7302886/143026685-cb384b18-f381-4cd0-8383-19cfd0ecf982.png)

```java
final DecimalFloat currentPrice;
currentPrice = DecimalFloat.ZERO;
assertThat(currentPrice.toString()).isEqualTo("0");

// When
currentPrice.set(new DecimalFloat(5));

assertThat(DecimalFloat.ZERO.toString()).isEqualTo("0");
```

As shown above, this is especially dangerous in the case when someone uses this constant to set the initial value of some field/variable in their codebase. If this initial value is subsequently updated, it affects all usages and zero becomes a non-zero value.
Also, providing a static mutable fields that looks like constants is probably misleading.

Can we discuss how we can make it less dangerous to use?

**Comment by vyazelenko** [comment]
The same is true of other constants such as `DecimalFloat#NAN` which is among other things is used to denote a missing value when parsing from ASCII (i.e. [uk.co.real_logic.artio.builder.CommonDecoderImpl#getFloat](https://github.com/real-logic/artio/blob/b297ea77f643c2758bc1c464b9fbacc5397a45f2/artio-codecs/src/main/java/uk/co/real_logic/artio/builder/CommonDecoderImpl.java#L83-L104)). In the parsing case once the parsing failed and the same flyweight is used again the `DecimalFloat#MISSING_FLOAT` will be mutated as a result of a successful parsing.

**Comment by RichardWarburton** [comment]
I think making them immutable is a good idea, you're right it does reduce the scope for errors here. I'm not sure what the best approach is mind.

One choice would be to introduce a parent class to DecimalFloat, eg: ImmutableDecimalFloat, that has the accessors but no mutating methods on. Constants could be changed to use this immutable version. It would be backwards incompatible at the API level but I think only in cases where a bug could happen, eg: calling a setter on DecimalFloat.NaN.

I'm open to other suggestions if there's a better option.

**Comment by vyazelenko** [comment]
Another way to solve it would be to add an `immutable` flag which could only be set via a private constructor. This way all constants would be declared with `immutable=true` while normal constructor will create mutable objects. Then you would have to add a check to every mutator method to ensure that object is mutable and throw otherwise, e.g.:
```java
    public DecimalFloat set(final DecimalFloat other)
    {
        if (immutable)
        {
            throw new IllegalStateException(this + " is immutable!");
        }
        this.value = other.value;
        this.scale = other.scale;
        return this;
    }
```

The downside of the approach is the checks which add overhead.

**Comment by vyazelenko** [comment]
@RichardWarburton As for the potential mutation of the constants consider the following snippet from the `uk.co.real_logic.artio.decoder.NewOrderSingleDecoder#decode` method:
```
            case Constants.ORDER_QTY:
                hasOrderQty = true;
                orderQty = getFloat(buffer, orderQty, valueOffset, valueLength, 38, CODEC_VALIDATION_ENABLED);
                break;
```

If you would call `NewOrderSingleDecoder#decode` with a missing a buffer that has no `ORDER_QTY` defined then the `orderQty` field will be assigned the `DecimalFloat.MISSING_FLOAT` value. Afterwards calling `NewOrderSingleDecoder#decode` with a data that has `ORDER_QTY` would lead to the mutation of `DecimalFloat.MISSING_FLOAT` constant, because `orderQty` field is passed to the `getFloat` method.

**Comment by RichardWarburton** [comment]
Yeah, I think adding a new class would be a better solution than adding the immutable flag. It puts the mutability information into the type and doesn't add the check. The main downside being the API change.

I think the orderQty example you've just mentioned can be fixed fairly easily by modifying the getFloat() method, thanks for pointing it out.

**Comment by michaelszymczak** [comment]
Thanks, all he comments make perfect sense. I tried to come up with the solution that you suggest in the last comment Richard and do it in a way that does not require any changes in the library clients' code (keeping in mind that they may already use the constants such as ZERO for comparison - maybe even as keys in maps - as value used to set another DecimalFloats etc.). If you have some time later this month, I will shortly send a pull request and appreciate any opinions/discussion.

**Comment by michaelszymczak** [comment]
The pull request fixing this issue is now ready: https://github.com/real-logic/artio/pull/454

**Comment by RichardWarburton** [comment]
Thanks @michaelszymczak - looks pretty good in general, a couple of minor inline comments to be addressed.

**Comment by michaelszymczak** [comment]
Thank you for taking time to review it @RichardWarburton . I have applied and pushed the changes you suggested in the latest commit.
