### ISSUE TITLE
More fluent way of transcoding optional strings from FIX to SBE

### ISSUE THREAD

**Issue by pcdv** [real-logic/artio#459]
Hi,

I'm copying fields from FIX messages to an SBE encoder. When the field is mandatory, this takes 2 lines because the first call returns void:

```java
      executionReportDecoder.account(asciiSequenceView);
      execReportEncoder.account(asciiSequenceView);
```

When the field is optional, this becomes more verbose to avoid getting an exception:

```java
    if (executionReportDecoder.hasAccount()) {
      executionReportDecoder.account(asciiSequenceView);
      execReportEncoder.account(asciiSequenceView);
    }
    else {
      execReportEncoder.account("");
    }
```

Notes:
 * the `accountAsString()` method does not throw an exception when the field is absent (it just returns null). But it generates garbage on the standard path
 * the account field here is a variable length field (I know this is not 100% in the spirit of SBE...), so it needs to be set even when undefined.

It looks like the code could fit on one line (with less branching) with the following modifications:

1. return `AsciiSequenceView` instead of void when wrapping the view
2. allow to remove the presence check: wrap zero bytes instead of throwing an exception

For example, the generated decoder method below:

```java
public void account(final AsciiSequenceView view)
{
    if (!hasAccount)
    {
        throw new IllegalArgumentException("No value for optional field: Account");
    }

    view.wrap(buffer, accountOffset, accountLength);
}
```
could become:

```java
public AsciiSequenceView account(final AsciiSequenceView view)
{
    return view.wrap(buffer, accountOffset, accountLength);
}
```
And the transcoding code would become:

```java
  execReportEncoder.account(executionReportDecoder.account(asciiSequenceView));
```
which behaves the same as the one above, has no branch, and allows chaining with other calls.

I suppose removing the presence check could be problematic for some people, so it could become a parameter in `CodecConfiguration`.

What do you think?

Thanks

**Comment by pcdv** [comment]
Looks like changing the return type from void to AsciiSequenceView has a bit of an impact and some signatures need to be updated in some interfaces that are implemented by generated decoders:
```
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/AbstractHeartbeatDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/AbstractLogonDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/AbstractLogoutDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/AbstractTestRequestDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/AbstractUserRequestDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/decoder/SessionHeaderDecoder.java
 M artio-codecs/src/main/java/uk/co/real_logic/artio/dictionary/generation/DecoderGenerator.java
```
Maybe this change would be too drastic to be applied by defaut and should also be configurable in CodecConfiguration?

**Comment by pcdv** [comment]
I'm afraid skipping the optional check altogether will corrupt the value of some fields, returning an indeterminate value, depending on previous buffer state. In this example, when `resetLastPx()` is called, only `hasLastPx` is reset, not `lastPx`.

```java
    public DecimalFloat lastPx()
    {
        if (!hasLastPx)
        {
            throw new IllegalArgumentException("No value for optional field: LastPx");
        }

        if (buffer != null && lastPxLength > 0)
        {
            lastPx = getFloatFlyweight(buffer, lastPx, lastPxOffset, lastPxLength, 31, CODEC_VALIDATION_ENABLED);
        }
        return lastPx;
    }
```

So, for the time being, I'm tempted to disable the optional check only for STRING fields and impact only methods accepting AsciiSequenceView.

**Comment by RichardWarburton** [comment]
I see, this feels like it results in quite inconsistent behaviour between
different field types if it throws for some and not others when enabled.
You could reset those other field values if its set, right? There are
defined MISSING_* values for the field types.

**Comment by tom-smalls** [comment]
I echo Richard's concerns. API calls with different side effects depending on the data type wouldn't be the most pleasant to use (we already have this to an extent with enum types, which is a bit annoying)

**Comment by pcdv** [comment]
I understand this concern. 

As the xxxAsString() getters already don't throw, it was not shocking to me that the AsciiSequenceView form would not throw either: wrapping an empty buffer does not look like an undesirable side effect. At worst, we have to deal with empty values in consumer code, and we can still call `hasXxx()` if we want.

I thought we could also improve performance along the way (by reducing code branches). But it turns out it is more complex than I thought: either we need to keep the branch, or we need to complexify the reset methods (wrt offset and length fields).

However, the calling code could still become much simpler if we don't have to duck exceptions and we can chain calls.

**Comment by RichardWarburton** [comment]
Yeah, I think it's fair to say that not everything is perfectly consistent at the moment but we definitely want changes that are going in the direction of more consistency and not less.

If you still want to progress with this change then I would be inclined to keep the branch in the accessor rather than the reset method, as users usually reset every field in a message but they don't actually read all the fields all the time.

**Comment by RichardWarburton** [comment]
I think you want to add a test similar to the DecoderGeneratorTest with the option switched on and tests for the difference in behaviour.

**Comment by pcdv** [comment]
Done [here](https://github.com/real-logic/artio/pull/460/files#diff-f03c908574dc2a94e7d650ae169074cfe97abd2beb93d085c616a87b498dcaf0)

**Comment by pcdv** [comment]
For those that encounter build issues after migration to 0.129, you probably have to re-generate your fix codecs. On my side, I had to run `./gradlew clean assemble` in the subproject that contains them.
