### ISSUE TITLE
Repeating group decoder not cleaning reference to 'next' when decoding a new message

### ISSUE THREAD

**Issue by lucianoviana** [real-logic/artio#525]
When a repeating group decode is called, it's not nullifying the reference of 'next' element. As a consequence of this, if a previous message was successfully processed and it had a number X of elements in the same repeating group, then any succeeding message that is decoded which has an invalid value in the repeating group count tag will not detect the malformed repeating group because of the existing 'next' refence from previous decoding.

Example: Consider the messages below with repeating groups given by tags 120 and 121:

```
String good = "8=FIX.4.4|9=71|35=0|115=abc|116=2|117=1.1|127=19700101-00:00:00.001|120=2|121=1|121=2|10=053|"
String bad_ = "8=FIX.4.4|9=71|35=0|115=abc|116=2|117=1.1|127=19700101-00:00:00.001|120=3|121=1|121=2|10=053|"

Decoder decoder = new Decoder();
decoder.decode(good);
decoder.reset();
decoder.decode(bad_);

```
then 

`decoder.validate() == true       //INCORRECT`

**Comment by lucianoviana** [comment]
this has been fixed on https://github.com/real-logic/artio/pull/528

**Comment by writeoncereadmany** [comment]
This fix makes the decoder no longer garbage free in the steady state: every time we receive a new message, we allocate a new repeating group decoder.

Can we fix this by, instead of nulling out the group decoder, just resetting its properties instead?

**Comment by lucianoviana** [comment]
apologies for the undesirable effect - and thx for reaching out. I'll fix this in the way you suggested, @writeoncereadmany . Cheers

**Comment by lucianoviana** [comment]
the bug is fixed - hope it's all good now 👍

**Comment by writeoncereadmany** [comment]
tyvm!
