### ISSUE TITLE
Repeating group decoder freshly allocated on each message, violating garbage free assumptions

### ISSUE THREAD

**Issue by writeoncereadmany** [real-logic/artio#532]
In trying to upgrade to latest Artio, we've found that the decoders are no longer garbage free in the steady state (thanks to our allocation tests). 

Specifically: when decoding messages with repeating groups, the repeating group decoder is now nulled out on reset, meaning instead of it being a lazily allocated reused field, it's now freshly allocated each decode.

This was implemented in https://github.com/real-logic/artio/issues/525: there are other potential approaches such as resetting the fields of the group decoder or giving it some sentinel value to show that it's now dirty.

**Comment by JackBeezer** [comment]
Thanks for raising this, we will take a look and update you with any progress.

**Comment by lucianoviana** [comment]
bug fix is now merged
